### ISSUE TITLE
memory leak when network ranges are incorrect

### ISSUE THREAD

**Issue by teancom** [cloudfoundry-incubator/spiff#36]
If you have a broken network range, like:
```
        static:
          - 10.20.4.10 - 10.10.4.50
```
(note it starts in 10.20.x.x and ends in 10.10.x.x). Currently, that causes spiff to use all available memory and die. Detecting that as a problem and spitting out an error would be a more ideal outcome.

**Comment by Amit-PivotalLabs** [comment]
Closing, spiff is not under active development, and no non-critical issues are being fixed.
