### ISSUE TITLE
spiff does not evaluate static_ips method if parameter has a trailing space

### ISSUE THREAD

**Issue by mavenraven** [cloudfoundry-incubator/spiff#46]
Given that hi.yml is

    networks:
    - name: cf1
      subnets:
      - cloud_properties:
          security_groups:
          - cf-0-vpc-c461c7a1
          subnet: subnet-e845bab1
        dns:
        - 10.60.3.2
        gateway: 10.60.3.1
        name: default_unused
        range: 10.60.3.0/24
        reserved:
        - 10.60.3.2 - 10.60.3.9
        static:
        - 10.60.3.10 - 10.60.3.70
      type: manual

and that bye.yml is

    networks: (( merge ))
    
    jobs:
      - name: myjob
        instances: 2
        networks:
        - name: mynetwork
          static_ips: (( static_ips(0, 3, 4 ) ))

.

    spiff merge bye.yml hi.yml 

returns

    jobs:
    - instances: 2
      name: myjob
      networks:
      - name: mynetwork
        static_ips: (( static_ips(0, 3, 4 ) ))
    networks:
    - name: cf1
      subnets:
      - cloud_properties:
          security_groups:
          - cf-0-vpc-c461c7a1
          subnet: subnet-e845bab1
        dns:
        - 10.60.3.2
        gateway: 10.60.3.1
        name: default_unused
        range: 10.60.3.0/24
        reserved:
        - 10.60.3.2 - 10.60.3.9
        static:
        - 10.60.3.10 - 10.60.3.70
      type: manual

It would be would be nice if this case either errored out, or ignored the trailing whitespace.

**Comment by Amit-PivotalLabs** [comment]
Closing, spiff is not under active development, and no non-critical issues are being fixed.
