### ISSUE TITLE
error: command '/usr/bin/gcc-4.8' failed with exit status 1

### ISSUE THREAD

**Issue by dzlab** [cloudfoundry-incubator/spiff#50]
I'm trying to install `spiff` on ubuntu 14.04.2 desktop, first I install linux brew:
```
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
$ export PATH=$PATH:/home/dzlab/.linuxbrew/bin
```
Then I try to install spiff:
```
$ brew install spiff
==> Installing spiff from xoebus/homebrew-cloudfoundry
==> Installing dependencies for spiff: mercurial, godep
==> Installing spiff dependency: mercurial
==> Downloading http://mercurial.selenic.com/release/mercurial-3.3.tar.gz
Already downloaded: /home/heavenize/.cache/Homebrew/mercurial-3.3.tar.gz
==> make PREFIX=/home/heavenize/.linuxbrew/Cellar/mercurial/3.3 install-bin
 #include <Python.h>
                                 ^
compilation terminated.
error: command '/usr/bin/gcc-4.8' failed with exit status 1
make: *** [build] Error 1

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
```
How I can fix this issue? is there another way to install `spiff` on ubuntu?

**Comment by Amit-PivotalLabs** [comment]
Hi @dzlab,

You should just use one of the official releases that can be downloaded from github [here](https://github.com/cloudfoundry-incubator/spiff/releases).  The stuff for Homebrew is a community contribution, you may wish to open an issue [there](https://github.com/xoebus/homebrew-cloudfoundry).  However I don't know if that repo was ever intended to support linuxbrew.

**Comment by dzlab** [comment]
Hi @Amit-PivotalLabs I should have closed this issue as I've end up using a latest spiff release.
