### ISSUE TITLE
Value tracing to source document

### ISSUE THREAD

**Issue by jim80net** [cloudfoundry-incubator/spiff#51]
As a bosh release writer who uses several stubs to generate a complete manifest, I want to supply spiff a command line argument, like --trace,  and receive lookup information that describes where spiff derived final values.

This might be in the form of a symmetrical yml file where values are swapped with filenames of the source document, or inline comment. The main intent is so that folks who use stubs can easily figure out how an unintended resultant value came to be and where to go to correct it. There is also cases of hash keys being blocked from the completed manifest, and this information would be illustrative of where to look for that as well.

**Comment by Amit-PivotalLabs** [comment]
Hey @jim80net,

`spiff` usage patterns have become increasingly complex, leading to things like users having no idea where values are supposed to come from.  We are pausing all active development on `spiff`, and working on a better, simpler, BOSH-smarter solution to manifest generation.

Thanks for your input,
Amit
