### ISSUE TITLE
error generating manifest: unresolved nodes

### ISSUE THREAD

**Issue by MyGoul** [cloudfoundry-incubator/spiff#57]
Hi all,

I'm trying to create my cf-deployment.yml to deploy CF via bosh. When i launch the command :

./generate_deployment_manifest openstack ../cf-stub.yml > cf-deployment.yml

I have the following error :

2015/04/29 05:31:53 error generating manifest: unresolved nodes:
	(( merge ))	in ./templates/cf-properties.yml	properties.uaa.clients.gorouter.secret	(properties.uaa.clients.gorouter.secret)

whereas i dont't find any mention of the properties.uaa.clients.gorouter.secret attribute neither in my ../cf-stub.yml, nor in my cf-deployment.yml.

Thanks in advance for your support.
Sylvain

**Comment by ematpl** [comment]
Hi, @MyGoul,

The spiff output is telling you that the cf-properties.yml template has an unresolved node, namely [this one](https://github.com/cloudfoundry/cf-release/blob/9eb841f2d1debc3cf05aadff896a42751116ccc3/templates/cf-properties.yml#L287). The `generate_deployment_manifest` script [merges several templates from cf-release](https://github.com/cloudfoundry/cf-release/blob/9eb841f2d1debc3cf05aadff896a42751116ccc3/generate_deployment_manifest#L17-L22) together with the stub you provide to generate a complete deployment manifest for CF, so you'll need to supply a value for that node in your own cf-stub.yml file.

Thanks,
Eric, for the CF Runtime Diego team

**Comment by MyGoul** [comment]
Sounds simple and it works :)

Thank you for your support.

**Comment by ematpl** [comment]
Glad to hear it! Closing this out.

Thanks again,
Eric
