### ISSUE TITLE
Add support for (( $env_var )) syntax

### ISSUE THREAD

**Issue by Nopik** [cloudfoundry-incubator/spiff#60]
Currently in order to blend in env var into .yml one needs to have template file, sed the placeholder for env var, then spiff merge - which basically defeats the purpose of using spiff. Adding this support (which I hope would be next to trivial) would reduce the boilerplate significantly.

**Comment by ematpl** [comment]
Hi, @Nopik,

Thanks for the suggestion. Do you have specific examples of stubs and templates with placeholders that you're trying to merge with environment variables? There may be other ways of building some minimal tooling around spiff to achieve what you want. In general, spiff's process of merging templates and stubs together is often confusing enough that I hesitate to add an additional, cross-cutting method of inputting values without strong justification.

Best,
Eric, CF Runtime Diego PM

**Comment by Nopik** [comment]
I'm building an bosh manifest in Concourse CI. I have some values in Concourse's credentials I'd like to pass as job properties in bosh. The shortest path I know now is to:
- define value in credentials.yml for CI
- pass value in pipeline as env var / arg to a task
- inside task have some template yml stub file
- sed the MY_VAR into $MY_VAR to actually substitute the passed value to the .yml
- spiff several .yml together
- do the rest of the pipeline

Being able to read env vars directly from spiff would allow me to skip some of the .yml files completely and skip the sed stage as well.

**Comment by vito** [comment]
I'm inclined to agree with @ematpl on this; I'd rather there not be two ways to provide values in a Spiff template given how complicated some use cases already are. You may want to just use ERB instead, which is supported natively by BOSH:

```erb
foo:
  bar: <%= ENV["BAR"] %>
```

(...In general I'd hope usage of spiff outside of CF is not increasing.)

**Comment by Amit-PivotalLabs** [comment]
Thanks for the suggestion @Nopik.  We are gradually moving away from spiff, and moving towards better tooling in BOSH itself.  We're heading towards a tool that is less able to do arbitrary things, but smarter about BOSH-deployment specific things.  As such, we're not planning any new feature development in spiff, or taking on additional features to maintain.

The typical pattern used by most BOSH users who are generating manifests is to have credentials in a stub checked into a private repository, and including that repo as a resource for whatever Concourse task you have generating your manifest.

Best,
Amit, CF OSS Release Integration PM
