### ISSUE TITLE
go get fails with "AnnotatedNode does not implement Node"

### ISSUE THREAD

**Issue by samof76** [cloudfoundry-incubator/spiff#61]
go verion: 1.4.2
system: ubuntu 14.04

    $ go get github.com/cloudfoundry-incubator/spiff
    # github.com/cloudfoundry-incubator/spiff/yaml
    gopath/src/github.com/cloudfoundry-incubator/spiff/yaml/node.go:23: cannot use AnnotatedNode literal (type AnnotatedNode) as type Node in return argument:
        AnnotatedNode does not implement Node (wrong type for MarshalYAML method)
            have MarshalYAML() (string, interface {})
            want MarshalYAML() (string, interface {}, error)
    gopath/src/github.com/cloudfoundry-incubator/spiff/yaml/parser.go:49: cannot use AnnotatedNode literal (type AnnotatedNode) as type Node in return argument:
        AnnotatedNode does not implement Node (wrong type for MarshalYAML method)
            have MarshalYAML() (string, interface {})
            want MarshalYAML() (string, interface {}, error)
    gopath/src/github.com/cloudfoundry-incubator/spiff/yaml/parser.go:63: cannot use AnnotatedNode literal (type AnnotatedNode) as type Node in return argument:
        AnnotatedNode does not implement Node (wrong type for MarshalYAML method)
            have MarshalYAML() (string, interface {})
            want MarshalYAML() (string, interface {}, error)
    gopath/src/github.com/cloudfoundry-incubator/spiff/yaml/parser.go:66: cannot use AnnotatedNode literal (type AnnotatedNode) as type Node in return argument:
        AnnotatedNode does not implement Node (wrong type for MarshalYAML method)
            have MarshalYAML() (string, interface {})
            want MarshalYAML() (string, interface {}, error)

**Comment by amitkgupta** [comment]
Hi @samof76, the spiff repo vendors in its dependencies in `Godeps/_workspace` using the [godeps](https://github.com/tools/godep) tool.  One would be to use the godep tool to restore the dependencies from the `Godeps` folder into your main `$GOPATH`, but this will overwrite what's already there.  Another alternative would just be to prepend the vendor directory to your `$GOPATH` while doing things like `go get`, so e.g. `GOPATH=$GOPATH/src/github.com/cloudfoundry-incubator/spiff/Godeps/_workspace:$GOPATH go get github.com/cloudfoundry-incubator/spiff`.  You can use something like [direnv](http://direnv.net/) so you don't need to prefix your `$GOPATH` every time you work out of the `spiff` directory.

Are you trying to work on the spiff code or are you just trying to install the spiff binary so you can use it?

**Comment by ematpl** [comment]
For context, this looks like fallout from a breaking change to the `Marshaler` interface in the candiedyaml library, introduced to resolve https://github.com/cloudfoundry-incubator/candiedyaml/issues/11. It may be simpler to update the spiff types to conform to the new interface.

**Comment by samof76** [comment]
@amitkgupta I am trying to install Spiff, as part of setting up CF.

**Comment by Amit-PivotalLabs** [comment]
Consider using an [official release](https://github.com/cloudfoundry-incubator/spiff/releases) rather than building from source.  Statically linked binaries for Darwin and Linux AMD64 architectures are provided.

**Comment by Amit-PivotalLabs** [comment]
Closing this issue, feel free to re-open or create a new issue if you have further questions.

**Comment by AnthonyMullerPlayground** [comment]
Hello,

As they are no official release for Windows users, how to workaround this issue since it is still present :(

Regards,
Anthony

**Comment by Amit-PivotalLabs** [comment]
Hey @AnthonyMullerPlayground 

The work around would be to use a Linux VM.  If you are deploying to BOSH-Lite, you can use the BOSH-Lite VM itself.  If you are deploying to a real IaaS, you may wish to set up a jumpbox in your IaaS from which you can do all your manifest generation and even deploying.  In production scenarios where you want even your BOSH director firewalled off from the Internet, it's common practice to have the director port 25555 only accessible from within the firewall, and have your jumpboxes be the only externally accessible thing (via SSH).
