### ISSUE TITLE
static url to download latest stable

### ISSUE THREAD

**Issue by shalako** [cloudfoundry-incubator/spiff#63]
I'd like to automate getting the latest stable release, rather than visiting the website and finding a link. Could you put a link on the README for the latest stable binary? 

cf CLI does this and it is very handy: https://github.com/cloudfoundry/cli#downloads

**Comment by Amit-PivotalLabs** [comment]
@shalako thanks for your suggestion.

We are not planning to continue active development on spiff, and will likely only perform maintenance for major issues.  The most recent release is likely to remain the latest stable release.  You can use the following links:

[linux binary](https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.7/spiff_linux_amd64.zip)
[darwin binary](https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.7/spiff_darwin_amd64.zip)

These are unfortunately zip files, so you would still need to unzip them (they yield a single executable file called `spiff`).

I know this situation isn't ideal, but is it sufficient for your requirements?

**Comment by shalako** [comment]
Yes, thank you. I don't expect to have to update spiff often.

**Comment by ematpl** [comment]
If you do want the download URL of the OS X binary for the latest spiff release, not just 1.0.7, you can retrieve it from the GitHub API with
```
curl -s https://api.github.com/repos/cloudfoundry-incubator/spiff/releases/latest | jq -r '.assets[] | select(.name=="spiff_darwin_amd64.zip") | .browser_download_url'
```
