### ISSUE TITLE
Spiff is not honest when handle ""

### ISSUE THREAD

**Issue by cdlliuy** [cloudfoundry-incubator/spiff#77]
I have the following YAML file, in which I hardcoded some key value pair and enclose with "". Then after running spiff to replace some parts of the `template.yml` (didn't attach here, since the merge works great), I found the hardcoded key value pair format are changed.  " -> ' or deleted ..  

Could spiff be honest to keep the "" part if no merge required, just copy the original one directly to output

template.yml:

```
foo:
  json: "{key: value}"	
  non-json: "key: value"
```

```
$ spiff merge template.yml:

foo:
  non-json: key: value
  json: '{key: value}'
```

**Comment by Amit-PivotalLabs** [comment]
Hi @cdlliuy 

I'm not sure why the single quotes vs double quotes matter, but removing the quotes altogether definitely seems like a big, since it will lead to invalid YAML.  That said, as noted in the README:

> Active development on `spiff` is currently paused, including Pull Requests. Very severe issues will be addressed, and we will still be actively responding to requests for help via Issues.

As this issue doesn't appear to be severe, I will close this issue at this time.
