### ISSUE TITLE
Precompiled binary fails on macOS Sierra

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/spiff#79]
I only tested version 1.0.7, and it fails under some circumstances with

```
failed MSpanList_Insert 0x51a140 0x38b6af607ebb 0x0
fatal error: MSpanList_Insert
```

I believe it is related to this bug: https://github.com/golang/go/issues/16352

I've recompiled spiff on Sierra using Go 1.7.3, and the new binary works fine. So maybe the binary releases for Darwin should be recompiled.

**Comment by jandubois** [comment]
Official doc link: https://golang.org/doc/go1.7#ports

> Go 1.7 adds support for macOS 10.12 Sierra. This support was backported to Go 1.6.3. Binaries built with versions of Go before 1.6.3 will not work correctly on Sierra.

**Comment by jadekler** [comment]
@jandubois Just tested on `MacOS 10.12.1` (sierra) spiff `1.0.7` and I had no problems.

**Comment by jadekler** [comment]
Same problem, after initially thinking it was fine, running this against `cf-release`'s `generate-manifest` caused the same issue.

**Comment by dsabeti** [comment]
Hey, @jandubois and @jadekler. Sorry for the delayed response on this. Spiff hasn't been under active development for a long time. However, it seems like this is going to break anybody who upgrades their OS, so I'd like to take care of it. 

@jandubois, is your impression that it's simply a matter of compiling spiff against go1.7?

**Comment by jandubois** [comment]
Hi @dsabeti. Yes, I just compiled `spiff` myself using 1.7.3 and everything worked after that.

All you have to do is to move the vendored components from `Godeps/` to `vendor/` for the new vendoring mechanism in 1.7 to pick things up, e.g.

```bash
mv Godeps/_workspace/src/* vendor/
```

**Comment by dsabeti** [comment]
@jandubois. Great, thanks. We'll try to get to it shortly.
