### ISSUE TITLE
spiff only generating {}

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry-incubator/spiff#81]
```
 2016-11-14 20:02:36 ☆  |2.3.0| DEN_Recently_Imaged in ~/workspace/cf-release
±  |master ?:1 ✗| → echo "foo: bar" > /tmp/foo.yml && spiff merge /tmp/foo.yml
{}
```

This is with a manually-built (`go build`) binary on OSX 10.12.1

**Comment by jadekler** [comment]
```
 2016-11-14 20:04:19 ☆  |2.3.0| DEN_Recently_Imaged in ~/workspace/spiff
±  |master ?:1 ✗| → go run spiff.go merge /tmp/foo.yml
{}
```

**Comment by dsabeti** [comment]
Hey @jadekler. What version of spiff are you running? And what OS is it running on?

**Comment by jadekler** [comment]
@dsabeti Latest OSX (Sierra / 10.12.1 I believe?) and latest spiff (1.0.7)

**Comment by dsabeti** [comment]
Ok, @jadekler my guess is that you're having the same problem as this: https://github.com/cloudfoundry-incubator/spiff/issues/79

I'm going to close this issue and continue the conversation on that thread.
