### ISSUE TITLE
Problem with spiff merge having code in yml

### ISSUE THREAD

**Issue by subhankarc** [cloudfoundry-incubator/spiff#85]
I have 3 yml file 0.yml, 1.yml and 2.yml.

Their contents are the following.

**0.yml**

    name: (( merge ))
    director_uuid: (( merge ))
    foo1: (( merge ))

**1.yml**

    <%
      director_uuid = `bosh status --uuid 2>/dev/null`.strip
    %>
    ---
    name: service-fabrik
    director_uuid: <%= director_uuid %>
    foo1: (( merge ))

**2.yml**

    foo1: bar1

If I do spiff merge 0.yml 1.yml 2.yml > 3.yml then 3.yml looks like this.

    foo1: bar1

I want it to be like the following :

    name: service-fabrik
    director_uuid: jfheifefefif
    foo1: bar1

But it does not work. If I remove the code part from 1.yml

    <%
      director_uuid = `bosh status --uuid 2>/dev/null`.strip
    %>

Then it works normally. But I want it. How do I make it work?

**Comment by dsabeti** [comment]
Hi @subhankarc.

The snippet of code you provided is [a Ruby-based templating language called ERB](http://www.stuartellis.name/articles/erb/), which is actually unrelated to `spiff`. In fact, I'm pretty sure that from `spiff`'s perspective, 1.yml is not a valid yaml file.

I think your best bet is to fill out the template in 1.yml using the `erb` command line tool, and then use spiff to merge the result with the other yaml files (0.yml and 2.yml).

**Comment by dsabeti** [comment]
Hi @subhankarc, I'm going to close the PR, but feel free to re-open it if you need more help.
